/*=====================================================
Magnitude Analysis:measues by dimensions
The process of quantifying and comparing key business 
metrics across dimensions to identify which categories, 
products, or customer segments contribute most significantly 
to overall results.
--=====================================================*/
--1.Total Customers for each counrty
select  country,count(customer_id) as total_cust from gold.dim_customers group by country order by total_cust desc;
 --2.Total customers for female and male
 select gender,count(customer_id) as total_cust_gender from gold.dim_customers group by gender order by total_cust_gender desc;
  --3.Average cost in each category
  select category,avg(cost) avg_cost from  gold.dim_products group by category order by avg_cost desc;
 --4.Total products by category
  select category,count(product_key) total_products from  gold.dim_products group by category order by total_products desc; 
 --5.To find total Revenue generated by each category
 select
	p.category,
	sum(f.sales_amount) total_revenue
from gold.fact_sales f
left join gold.dim_products p
on f.product_key=p.product_key
group by p.category
order by total_revenue;

 --6.Total revenue generated by each customer
 select
	 c.customer_key,
	 c.first_name,
	 c.last_name,
	 sum(f.sales_amount) total_revenue1
 from gold.fact_sales f
 left join gold.dim_customers c
 on f.customer_key=c.customer_key
 group by c.customer_key,c.first_name,c.last_name
 order by total_revenue1 desc;
 --7.Total items sold in each country
 select
	 c.country,
	 sum(f.quantity) total_items_sold
 from gold.fact_sales f
 left join gold.dim_customers c
 on f.customer_key=c.customer_key
 group by c.country
 order by total_items_sold desc;
